

### 

GET http://localhost:9090
Accept: application/json

###

GET http://localhost:9090/users
Accept: application/json

###


GET http://localhost:9090/users/101
Accept: application/json
### 

GET http://localhost:9090/users/obj/101
Accept: application/json


###
GET http://localhost:9090/users/hateoas/101
Accept: application/json

### 
POST http://localhost:9090/users
Accept: application/json
Content-Type: application/json

{
  "id": 104,
  "name": "Akhil",
  "income": 2323.0,
  "dob": "2021-06-30T06:26:14.450+00:00"
}

### 



GET http://localhost:8761/


### 
GET http://localhost:9090/user


### 
GET http://localhost:8765/USER/user


### 
GET http://localhost:8765/USER-ADDRESS/user-address



